"""initial migration

Revision ID: 5298035c1af1
Revises: 
Create Date: 2025-05-26 10:26:39.183242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5298035c1af1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_en', sa.String(length=255), nullable=False),
    sa.Column('domain_fr', sa.String(length=255), nullable=False),
    sa.Column('subdomains_en', sa.JSON(), nullable=True),
    sa.Column('subdomains_fr', sa.JSON(), nullable=True),
    sa.Column('english_term', sa.String(length=255), nullable=False),
    sa.Column('french_term', sa.String(length=255), nullable=False),
    sa.Column('semantic_label_en', sa.String(length=255), nullable=True),
    sa.Column('semantic_label_fr', sa.String(length=255), nullable=True),
    sa.Column('variant_en', sa.String(length=255), nullable=True),
    sa.Column('variant_fr', sa.String(length=255), nullable=True),
    sa.Column('near_synonym_en', sa.String(length=255), nullable=True),
    sa.Column('near_synonym_fr', sa.String(length=255), nullable=True),
    sa.Column('definition_en', sa.Text(), nullable=True),
    sa.Column('definition_fr', sa.Text(), nullable=True),
    sa.Column('syntactic_cooccurrence_en', sa.JSON(), nullable=True),
    sa.Column('syntactic_cooccurrence_fr', sa.JSON(), nullable=True),
    sa.Column('lexical_relations_en', sa.JSON(), nullable=True),
    sa.Column('lexical_relations_fr', sa.JSON(), nullable=True),
    sa.Column('note_en', sa.Text(), nullable=True),
    sa.Column('note_fr', sa.Text(), nullable=True),
    sa.Column('not_to_be_confused_with_en', sa.JSON(), nullable=True),
    sa.Column('not_to_be_confused_with_fr', sa.JSON(), nullable=True),
    sa.Column('frequent_expression_en', sa.JSON(), nullable=True),
    sa.Column('frequent_expression_fr', sa.JSON(), nullable=True),
    sa.Column('phraseology_en', sa.Text(), nullable=True),
    sa.Column('phraseology_fr', sa.Text(), nullable=True),
    sa.Column('context_en', sa.Text(), nullable=True),
    sa.Column('context_fr', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tid'),
    sa.UniqueConstraint('english_term'),
    sa.UniqueConstraint('english_term', 'french_term', name='unique_terms'),
    sa.UniqueConstraint('french_term')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'email', name='unique_terms')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('terms')
    # ### end Alembic commands ###
