"""update models by adding 'synonym'/'synonyme' fields

Revision ID: 6f2e3ca8b6d3
Revises: 5298035c1af1
Create Date: 2025-05-26 10:52:48.185103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2e3ca8b6d3'
down_revision = '5298035c1af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synonym_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('synonym_fr', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_column('synonym_fr')
        batch_op.drop_column('synonym_en')

    # ### end Alembic commands ###
