# Generated by Django 5.1.5 on 2025-03-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
