# Generated by Django 5.1.5 on 2025-03-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='src',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
