# .github/workflows/deploy.yml
name: Deploy Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Linode and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.LINODE_IP }}
          username: root
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            cd /var/www/glotecht
            git pull origin main --exclude=instance/
            source venv/bin/activate
            pip install -r requirements.txt
            flask db upgrade
            systemctl restart glotecht
            systemctl restart nginx
