name: Deploy Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Linode and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.LINODE_IP }}
          username: root
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            cd /var/www/glotecht
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt

            # Restart using systemd (Recommended)
            sudo systemctl daemon-reload
            sudo systemctl restart glotecht
            sudo systemctl restart nginx

            # If systemd is not working, use screen instead:
            screen -S flask-app -X quit || true  # Kill existing screen session
            screen -dmS flask-app bash -c "cd /var/www/glotecht && source venv/bin/activate && gunicorn -w 3 -b 0.0.0.0:8000 run:flask_app"
